# Generated by Django 5.1.1 on 2024-10-02 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0002_bookstore_pages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookStore',
            new_name='BookModel',
        ),
    ]
